{
  "extends": "eslint:recommended",
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "plugins": [
    "react",
    "flowtype"
  ],
  "rules": {
    "no-debugger": 0,
    "no-console": 0,
    "new-cap": 0,
    "strict": 0,
    "no-underscore-dangle": 0,
    "no-use-before-define": 0,
    "eol-last": 0,
    "quotes": [2, "single"],
    "jsx-quotes": [1, "prefer-double"],
    "react/jsx-no-undef": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-multi-comp": 1,
    "react/prefer-es6-class": 1,
    "react/jsx-pascal-case": 1,
    "react/jsx-closing-bracket-location": 1,
    "react/jsx-curly-spacing": 1,
    "react/jsx-boolean-value": 1,
    "react/no-string-refs": 1,
    "react/jsx-wrap-multilines": 1,
    "react/self-closing-comp": 1,
    "react/jsx-no-bind": 0,
    "react/sort-comp": 1,
    "react/no-is-mounted": 1
  },
  "globals": {
    "Iterable": true
  }
}